#! /bin/sh
# /etc/init.d/loadonboot

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script which will start / stop a program a boot /$
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Hello!"
	sudo service motion stop
	sudo modprobe i2c-dev
	sudo gpsd /dev/ttyAMA0 -F /var/run/gpsd.sock
    sleep 2s
    sudo python /home/pi/GPSLogger/main.py
    ;;
  stop)
    ;;
  *)
    echo "Bye!"
    sleep 2s
    killall python
    exit 1
    ;;
esac

exit 0